language: minimal

services:
  - docker

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - docker pull node:18
  - docker run -v $PWD:/app -w /app node:18 npm ci

script:
  - docker run -v $PWD:/app -w /app node:18 npm run e2e
